versions:
  v2.0:
    extends: v1.0
  v3.0:
    extends: v2.0
  v1.0:
    uri: ${url}
    status: beta
    methods:
      Foo:
        category: Foo
        uri: /endpoint
        description: >
          Sample request
      Bar:
        category: Foo
        uri: /endpoint
        description: >
          Sample request
      Baz:
        category: Foo2
        uri: /endpoint
        description: >
          Sample request
      Qux:
        category: Foo2
        uri: /endpoint
        description: >
          Sample request
