versions:
  v2.0:
    extends: v1.0
  v3.0:
    extends: v2.0
  v1.0:
    uri: ${url}
    status: beta
    sections:
      Foo:
        methods:
          Bar:
            uri: /endpoint
            description: >
              Sample request
          Baz:
            uri: /endpoint
            description: >
              Sample request
      Foo2:
        methods:
          Bar:
            uri: /endpoint
            description: >
              Sample request
          Baz:
            uri: /endpoint
            description: >
              Sample request
